
export interface RawCatalogBrand {
  brand: string;
  slug: string;
  models: { name: string; slug: string }[];
}

export const AUTOMOTIVE_CATALOG: RawCatalogBrand[] = [
  {
    brand: "BMW",
    slug: "bmw",
    models: [
      { name: "Serija 1", slug: "1-series" }, { name: "114", slug: "114" }, { name: "116", slug: "116" }, { name: "118", slug: "118" }, { name: "120", slug: "120" }, { name: "123", slug: "123" }, { name: "125", slug: "125" }, { name: "130", slug: "130" }, { name: "135", slug: "135" }, { name: "M135i", slug: "m135i" }, { name: "M140i", slug: "m140i" },
      { name: "Serija 2", slug: "2-series" }, { name: "214", slug: "214" }, { name: "216", slug: "216" }, { name: "218", slug: "218" }, { name: "220", slug: "220" }, { name: "225", slug: "225" }, { name: "M235i", slug: "m235i" }, { name: "M240i", slug: "m240i" }, { name: "Active Tourer", slug: "active-tourer" }, { name: "Gran Tourer", slug: "gran-tourer" },
      { name: "Serija 3", slug: "3-series" }, { name: "316", slug: "316" }, { name: "318", slug: "318" }, { name: "320", slug: "320" }, { name: "323", slug: "323" }, { name: "325", slug: "325" }, { name: "328", slug: "328" }, { name: "330", slug: "330" }, { name: "335", slug: "335" }, { name: "340", slug: "340" }, { name: "M340i", slug: "m340i" }, { name: "318 Gran Turismo", slug: "318-gt" }, { name: "320 Gran Turismo", slug: "320-gt" }, { name: "328 Gran Turismo", slug: "328-gt" }, { name: "330 Gran Turismo", slug: "330-gt" }, { name: "335 Gran Turismo", slug: "335-gt" },
      { name: "Serija 4", slug: "4-series" }, { name: "418", slug: "418" }, { name: "420", slug: "420" }, { name: "425", slug: "425" }, { name: "428", slug: "428" }, { name: "430", slug: "430" }, { name: "435", slug: "435" }, { name: "440", slug: "440" }, { name: "M440i", slug: "m440i" }, { name: "Gran Coupe", slug: "gran-coupe" },
      { name: "Serija 5", slug: "5-series" }, { name: "518", slug: "518" }, { name: "520", slug: "520" }, { name: "523", slug: "523" }, { name: "524", slug: "524" }, { name: "525", slug: "525" }, { name: "528", slug: "528" }, { name: "530", slug: "530" }, { name: "535", slug: "535" }, { name: "540", slug: "540" }, { name: "545", slug: "545" }, { name: "550", slug: "550" }, { name: "M550i", slug: "m550i" }, { name: "M550d", slug: "m550d" }, { name: "520 Gran Turismo", slug: "520-gt" }, { name: "530 Gran Turismo", slug: "530-gt" }, { name: "535 Gran Turismo", slug: "535-gt" }, { name: "550 Gran Turismo", slug: "550-gt" },
      { name: "Serija 6", slug: "6-series" }, { name: "630", slug: "630" }, { name: "635", slug: "635" }, { name: "640", slug: "640" }, { name: "645", slug: "645" }, { name: "650", slug: "650" }, { name: "630 Gran Turismo", slug: "630-gt" }, { name: "640 Gran Turismo", slug: "640-gt" },
      { name: "Serija 7", slug: "7-series" }, { name: "725", slug: "725" }, { name: "728", slug: "728" }, { name: "730", slug: "730" }, { name: "735", slug: "735" }, { name: "740", slug: "740" }, { name: "745", slug: "745" }, { name: "750", slug: "750" }, { name: "760", slug: "760" }, { name: "M760Li", slug: "m760li" },
      { name: "Serija 8", slug: "8-series" }, { name: "840", slug: "840" }, { name: "850", slug: "850" }, { name: "M850i", slug: "m850i" },
      { name: "X1", slug: "x1" }, { name: "X1 16d", slug: "x1-16d" }, { name: "X1 18d", slug: "x1-18d" }, { name: "X1 20d", slug: "x1-20d" }, { name: "X1 23d", slug: "x1-23d" }, { name: "X1 25d", slug: "x1-25d" }, { name: "X1 18i", slug: "x1-18i" }, { name: "X1 20i", slug: "x1-20i" }, { name: "X1 25i", slug: "x1-25i" }, { name: "X1 28i", slug: "x1-28i" },
      { name: "X2", slug: "x2" }, { name: "X2 18d", slug: "x2-18d" }, { name: "X2 20d", slug: "x2-20d" }, { name: "X2 25d", slug: "x2-25d" }, { name: "X2 18i", slug: "x2-18i" }, { name: "X2 20i", slug: "x2-20i" }, { name: "X2 M35i", slug: "x2-m35i" },
      { name: "X3", slug: "x3" }, { name: "X3 18d", slug: "x3-18d" }, { name: "X3 2.0d", slug: "x3-2-0d" }, { name: "X3 3.0d", slug: "x3-3-0d" }, { name: "X3 3.0sd", slug: "x3-3-0sd" }, { name: "X3 30d", slug: "x3-30d" }, { name: "X3 35d", slug: "x3-35d" }, { name: "X3 M40d", slug: "x3-m40d" }, { name: "X3 2.0i", slug: "x3-2-0i" }, { name: "X3 2.5i", slug: "x3-2-5i" }, { name: "X3 3.0i", slug: "x3-3-0i" }, { name: "X3 20i", slug: "x3-20i" }, { name: "X3 28i", slug: "x3-28i" }, { name: "X3 30i", slug: "x3-30i" }, { name: "X3 35i", slug: "x3-35i" }, { name: "X3 M40i", slug: "x3-m40i" },
      { name: "X4", slug: "x4" }, { name: "X4 20d", slug: "x4-20d" }, { name: "X4 30d", slug: "x4-30d" }, { name: "X4 35d", slug: "x4-35d" }, { name: "X4 M40d", slug: "x4-m40d" }, { name: "X4 20i", slug: "x4-20i" }, { name: "X4 28i", slug: "x4-28i" }, { name: "X4 30i", slug: "x4-30i" }, { name: "X4 35i", slug: "x4-35i" }, { name: "X4 M40i", slug: "x4-m40i" },
      { name: "X5", slug: "x5" }, { name: "X5 3.0d", slug: "x5-3-0d" }, { name: "X5 3.0sd", slug: "x5-3-0sd" }, { name: "X5 30d", slug: "x5-30d" }, { name: "X5 35d", slug: "x5-35d" }, { name: "X5 40d", slug: "x5-40d" }, { name: "X5 M50d", slug: "x5-m50d" }, { name: "X5 3.0i", slug: "x5-3-0i" }, { name: "X5 4.4i", slug: "x5-4-4i" }, { name: "X5 4.6is", slug: "x5-4-6is" }, { name: "X5 4.8is", slug: "x5-4-8is" }, { name: "X5 35i", slug: "x5-35i" }, { name: "X5 40i", slug: "x5-40i" }, { name: "X5 48i", slug: "x5-48i" }, { name: "X5 50i", slug: "x5-50i" }, { name: "X5 M50i", slug: "x5-m50i" }, { name: "X5 40e", slug: "x5-40e" }, { name: "X5 45e", slug: "x5-45e" }, { name: "X5 50e", slug: "x5-50e" },
      { name: "X6", slug: "x6" }, { name: "X6 30d", slug: "x6-30d" }, { name: "X6 35d", slug: "x6-35d" }, { name: "X6 40d", slug: "x6-40d" }, { name: "X6 M50d", slug: "x6-m50d" }, { name: "X6 35i", slug: "x6-35i" }, { name: "X6 40i", slug: "x6-40i" }, { name: "X6 50i", slug: "x6-50i" }, { name: "X6 M50i", slug: "x6-m50i" },
      { name: "X7", slug: "x7" }, { name: "X7 30d", slug: "x7-30d" }, { name: "X7 40d", slug: "x7-40d" }, { name: "X7 M50d", slug: "x7-m50d" }, { name: "X7 40i", slug: "x7-40i" }, { name: "X7 M50i", slug: "x7-m50i" }, { name: "X7 M60i", slug: "x7-m60i" },
      { name: "Z3", slug: "z3" }, { name: "Z4", slug: "z4" }, { name: "i3", slug: "i3" }, { name: "i4", slug: "i4" }, { name: "i7", slug: "i7" }, { name: "i8", slug: "i8" }, { name: "iX", slug: "ix" }, { name: "iX1", slug: "ix1" }, { name: "iX3", slug: "ix3" },
      { name: "M2", slug: "m2" }, { name: "M3", slug: "m3" }, { name: "M4", slug: "m4" }, { name: "M5", slug: "m5" }, { name: "M6", slug: "m6" }, { name: "M8", slug: "m8" }, { name: "X3 M", slug: "x3-m" }, { name: "X4 M", slug: "x4-m" }, { name: "X5 M", slug: "x5-m" }, { name: "X6 M", slug: "x6-m" },
      { name: "E30", slug: "e30" }, { name: "E36", slug: "e36" }, { name: "E46", slug: "e46" }, { name: "E90", slug: "e90" }, { name: "E91", slug: "e91" }, { name: "E92", slug: "e92" }, { name: "E93", slug: "e93" }, { name: "E60", slug: "e60" }, { name: "E61", slug: "e61" }, { name: "F10", slug: "f10" }, { name: "F11", slug: "f11" }, { name: "F30", slug: "f30" }, { name: "F31", slug: "f31" }, { name: "G20", slug: "g20" }, { name: "G30", slug: "g30" }
    ]
  },
  {
    brand: "Volkswagen",
    slug: "volkswagen",
    models: [
      { name: "Golf 1", slug: "golf-1" }, { name: "Golf 2", slug: "golf-2" }, { name: "Golf 3", slug: "golf-3" }, { name: "Golf 4", slug: "golf-4" }, { name: "Golf 5", slug: "golf-5" }, { name: "Golf 6", slug: "golf-6" }, { name: "Golf 7", slug: "golf-7" }, { name: "Golf 8", slug: "golf-8" }, { name: "Golf Plus", slug: "golf-plus" }, { name: "Golf Sportsvan", slug: "golf-sportsvan" }, { name: "Golf Variant", slug: "golf-variant" },
      { name: "Passat B1", slug: "passat-b1" }, { name: "Passat B2", slug: "passat-b2" }, { name: "Passat B3", slug: "passat-b3" }, { name: "Passat B4", slug: "passat-b4" }, { name: "Passat B5", slug: "passat-b5" }, { name: "Passat B5.5", slug: "passat-b5-5" }, { name: "Passat B6", slug: "passat-b6" }, { name: "Passat B7", slug: "passat-b7" }, { name: "Passat B8", slug: "passat-b8" }, { name: "Passat CC", slug: "passat-cc" }, { name: "Passat Alltrack", slug: "passat-alltrack" },
      { name: "Polo", slug: "polo" }, { name: "Polo Sedan", slug: "polo-sedan" }, { name: "Polo Variant", slug: "polo-variant" },
      { name: "Tiguan", slug: "tiguan" }, { name: "Tiguan Allspace", slug: "tiguan-allspace" },
      { name: "Touareg", slug: "touareg" }, { name: "Touareg R", slug: "touareg-r" },
      { name: "Touran", slug: "touran" }, { name: "Arteon", slug: "arteon" }, { name: "Arteon Shooting Brake", slug: "arteon-sb" },
      { name: "T-Roc", slug: "t-roc" }, { name: "T-Roc Cabriolet", slug: "t-roc-cabrio" },
      { name: "T-Cross", slug: "t-cross" }, { name: "Taigo", slug: "taigo" },
      { name: "ID.3", slug: "id-3" }, { name: "ID.4", slug: "id-4" }, { name: "ID.5", slug: "id-5" }, { name: "ID.7", slug: "id-7" }, { name: "ID.Buzz", slug: "id-buzz" },
      { name: "Caddy", slug: "caddy" }, { name: "Caddy Maxi", slug: "caddy-maxi" }, { name: "Caddy Life", slug: "caddy-life" },
      { name: "Transporter T1", slug: "t1" }, { name: "Transporter T2", slug: "t2" }, { name: "Transporter T3", slug: "t3" }, { name: "Transporter T4", slug: "t4" }, { name: "Transporter T5", slug: "t5" }, { name: "Transporter T6", slug: "t6" }, { name: "Transporter T7", slug: "t7" },
      { name: "Multivan", slug: "multivan" }, { name: "Caravelle", slug: "caravelle" }, { name: "California", slug: "california" },
      { name: "Amarok", slug: "amarok" }, { name: "Bora", slug: "bora" }, { name: "Jetta", slug: "jetta" },
      { name: "Scirocco", slug: "scirocco" }, { name: "Sharan", slug: "sharan" }, { name: "Up!", slug: "up" },
      { name: "Lupo", slug: "lupo" }, { name: "Fox", slug: "fox" }, { name: "Corrado", slug: "corrado" },
      { name: "Eos", slug: "eos" }, { name: "New Beetle", slug: "new-beetle" }, { name: "Beetle", slug: "beetle" },
      { name: "Phaeton", slug: "phaeton" }, { name: "Vento", slug: "vento" }, { name: "Santana", slug: "santana" }
    ]
  },
  {
    brand: "Audi",
    slug: "audi",
    models: [
      { name: "A1", slug: "a1" }, { name: "A1 Sportback", slug: "a1-sportback" }, { name: "A1 Citycarver", slug: "a1-citycarver" },
      { name: "A2", slug: "a2" },
      { name: "A3", slug: "a3" }, { name: "A3 Sportback", slug: "a3-sportback" }, { name: "A3 Sedan", slug: "a3-sedan" }, { name: "A3 Cabriolet", slug: "a3-cabrio" },
      { name: "A4", slug: "a4" }, { name: "A4 Avant", slug: "a4-avant" }, { name: "A4 Allroad", slug: "a4-allroad" }, { name: "A4 Cabriolet", slug: "a4-cabrio" },
      { name: "A5", slug: "a5" }, { name: "A5 Sportback", slug: "a5-sportback" }, { name: "A5 Coupe", slug: "a5-coupe" }, { name: "A5 Cabriolet", slug: "a5-cabrio" },
      { name: "A6", slug: "a6" }, { name: "A6 Avant", slug: "a6-avant" }, { name: "A6 Allroad", slug: "a6-allroad" },
      { name: "A7", slug: "a7" }, { name: "A7 Sportback", slug: "a7-sportback" },
      { name: "A8", slug: "a8" }, { name: "A8 L", slug: "a8-l" },
      { name: "Q2", slug: "q2" }, { name: "Q3", slug: "q3" }, { name: "Q3 Sportback", slug: "q3-sportback" },
      { name: "Q4 e-tron", slug: "q4-e-tron" }, { name: "Q4 Sportback e-tron", slug: "q4-sb-e-tron" },
      { name: "Q5", slug: "q5" }, { name: "Q5 Sportback", slug: "q5-sportback" },
      { name: "Q7", slug: "q7" }, { name: "Q8", slug: "q8" }, { name: "Q8 e-tron", slug: "q8-e-tron" },
      { name: "e-tron", slug: "e-tron" }, { name: "e-tron GT", slug: "e-tron-gt" },
      { name: "TT", slug: "tt" }, { name: "TT Coupe", slug: "tt-coupe" }, { name: "TT Roadster", slug: "tt-roadster" },
      { name: "R8", slug: "r8" }, { name: "R8 Spyder", slug: "r8-spyder" },
      { name: "80", slug: "80" }, { name: "80 Avant", slug: "80-avant" }, { name: "80 Cabriolet", slug: "80-cabrio" },
      { name: "90", slug: "90" }, { name: "100", slug: "100" }, { name: "100 Avant", slug: "100-avant" }, { name: "200", slug: "200" },
      { name: "S1", slug: "s1" }, { name: "S3", slug: "s3" }, { name: "S4", slug: "s4" }, { name: "S5", slug: "s5" }, { name: "S6", slug: "s6" }, { name: "S7", slug: "s7" }, { name: "S8", slug: "s8" },
      { name: "RS3", slug: "rs3" }, { name: "RS4", slug: "rs4" }, { name: "RS5", slug: "rs5" }, { name: "RS6", slug: "rs6" }, { name: "RS7", slug: "rs7" },
      { name: "RS Q3", slug: "rs-q3" }, { name: "RS Q8", slug: "rs-q8" }, { name: "SQ2", slug: "sq2" }, { name: "SQ5", slug: "sq5" }, { name: "SQ7", slug: "sq7" }, { name: "SQ8" , slug: "sq8" }
    ]
  },
  {
    brand: "Mercedes-Benz",
    slug: "mercedes-benz",
    models: [
      { name: "A-Klasa", slug: "a-class" }, { name: "A 140", slug: "a-140" }, { name: "A 150", slug: "a-150" }, { name: "A 160", slug: "a-160" }, { name: "A 170", slug: "a-170" }, { name: "A 180", slug: "a-180" }, { name: "A 190", slug: "a-190" }, { name: "A 200", slug: "a-200" }, { name: "A 210", slug: "a-210" }, { name: "A 220", slug: "a-220" }, { name: "A 250", slug: "a-250" }, { name: "A 35 AMG", slug: "a-35-amg" }, { name: "A 45 AMG", slug: "a-45-amg" },
      { name: "B-Klasa", slug: "b-class" }, { name: "B 150", slug: "b-150" }, { name: "B 160", slug: "b-160" }, { name: "B 170", slug: "b-170" }, { name: "B 180", slug: "b-180" }, { name: "B 200", slug: "b-200" }, { name: "B 220", slug: "b-220" }, { name: "B 250", slug: "b-250" },
      { name: "C-Klasa", slug: "c-class" }, { name: "C 160", slug: "c-160" }, { name: "C 180", slug: "c-180" }, { name: "C 200", slug: "c-200" }, { name: "C 220", slug: "c-220" }, { name: "C 230", slug: "c-230" }, { name: "C 240", slug: "c-240" }, { name: "C 250", slug: "c-250" }, { name: "C 270", slug: "c-270" }, { name: "C 280", slug: "c-280" }, { name: "C 300", slug: "c-300" }, { name: "C 320", slug: "c-320" }, { name: "C 350", slug: "c-350" }, { name: "C 400", slug: "c-400" }, { name: "C 43 AMG", slug: "c-43-amg" }, { name: "C 63 AMG", slug: "c-63-amg" },
      { name: "E-Klasa", slug: "e-class" }, { name: "E 200", slug: "e-200" }, { name: "E 220", slug: "e-220" }, { name: "E 230", slug: "e-230" }, { name: "E 240", slug: "e-240" }, { name: "E 250", slug: "e-250" }, { name: "E 260", slug: "e-260" }, { name: "E 270", slug: "e-270" }, { name: "E 280", slug: "e-280" }, { name: "E 290", slug: "e-290" }, { name: "E 300", slug: "e-300" }, { name: "E 320", slug: "e-320" }, { name: "E 350", slug: "e-350" }, { name: "E 400", slug: "e-400" }, { name: "E 420", slug: "e-420" }, { name: "E 430", slug: "e-430" }, { name: "E 500", slug: "e-500" }, { name: "E 43 AMG", slug: "e-43-amg" }, { name: "E 53 AMG", slug: "e-53-amg" }, { name: "E 63 AMG", slug: "e-63-amg" },
      { name: "S-Klasa", slug: "s-class" }, { name: "S 280", slug: "s-280" }, { name: "S 300", slug: "s-300" }, { name: "S 320", slug: "s-320" }, { name: "S 350", slug: "s-350" }, { name: "S 400", slug: "s-400" }, { name: "S 420", slug: "s-420" }, { name: "S 430", slug: "s-430" }, { name: "S 450", slug: "s-450" }, { name: "S 500", slug: "s-500" }, { name: "S 550", slug: "s-550" }, { name: "S 560", slug: "s-560" }, { name: "S 600", slug: "s-600" }, { name: "S 63 AMG", slug: "s-63-amg" }, { name: "S 65 AMG", slug: "s-65-amg" },
      { name: "CLA", slug: "cla" }, { name: "CLS", slug: "cls" }, { name: "GLA", slug: "gla" }, { name: "GLB", slug: "glb" }, { name: "GLC", slug: "glc" }, { name: "GLE", slug: "gle" }, { name: "GLS", slug: "gls" }, { name: "GLK", slug: "glk" }, { name: "GL", slug: "gl" }, { name: "ML", slug: "ml" }, { name: "G-Klasa", slug: "g-class" },
      { name: "EQA", slug: "eqa" }, { name: "EQB", slug: "eqb" }, { name: "EQC", slug: "eqc" }, { name: "EQE", slug: "eqe" }, { name: "EQS", slug: "eqs" }, { name: "EQV", slug: "eqv" },
      { name: "SL", slug: "sl" }, { name: "SLC", slug: "slc" }, { name: "SLK", slug: "slk" }, { name: "SLS", slug: "sls" }, { name: "AMG GT", slug: "amg-gt" }, { name: "AMG GT 4-Door", slug: "amg-gt-4-door" },
      { name: "V-Klasa", slug: "v-class" }, { name: "Vito", slug: "vito" }, { name: "Sprinter", slug: "sprinter" }, { name: "Citan", slug: "citan" }, { name: "Viano", slug: "viano" },
      { name: "W123", slug: "w123" }, { name: "W124", slug: "w124" }, { name: "W201 (190)", slug: "w201" }, { name: "W210", slug: "w210" }, { name: "W211", slug: "w211" }, { name: "W212", slug: "w212" }, { name: "W220", slug: "w220" }, { name: "W221", slug: "w221" }
    ]
  },
  {
    brand: "Skoda",
    slug: "skoda",
    models: [
      { name: "Octavia", slug: "octavia" }, { name: "Octavia Tour", slug: "octavia-tour" }, { name: "Octavia Combi", slug: "octavia-combi" }, { name: "Octavia RS", slug: "octavia-rs" }, { name: "Octavia Scout", slug: "octavia-scout" },
      { name: "Superb", slug: "superb" }, { name: "Superb Combi", slug: "superb-combi" }, { name: "Superb iV", slug: "superb-iv" },
      { name: "Fabia", slug: "fabia" }, { name: "Fabia Combi", slug: "fabia-combi" }, { name: "Fabia RS", slug: "fabia-rs" }, { name: "Fabia Sedan", slug: "fabia-sedan" },
      { name: "Kodiaq", slug: "kodiaq" }, { name: "Kodiaq RS", slug: "kodiaq-rs" },
      { name: "Karoq", slug: "karoq" }, { name: "Kamiq", slug: "kamiq" },
      { name: "Scala", slug: "scala" }, { name: "Enyaq", slug: "enyaq" }, { name: "Enyaq Coupe", slug: "enyaq-coupe" },
      { name: "Rapid", slug: "rapid" }, { name: "Rapid Spaceback", slug: "rapid-spaceback" },
      { name: "Yeti", slug: "yeti" }, { name: "Roomster", slug: "roomster" }, { name: "Roomster Praktik", slug: "praktik" },
      { name: "Citigo", slug: "citigo" }, { name: "Felicia", slug: "felicia" }, { name: "Felicia Pick-up", slug: "felicia-pickup" }, { name: "Favorit", slug: "favorit" }, { name: "Forman", slug: "forman" }, { name: "105", slug: "105" }, { name: "120", slug: "120" }, { name: "130", slug: "130" }
    ]
  },
  {
    brand: "Toyota",
    slug: "toyota",
    models: [
      { name: "Corolla", slug: "corolla" }, { name: "Corolla Cross", slug: "corolla-cross" }, { name: "Corolla Verso", slug: "corolla-verso" },
      { name: "Yaris", slug: "yaris" }, { name: "Yaris Cross", slug: "yaris-cross" }, { name: "GR Yaris", slug: "gr-yaris" },
      { name: "RAV4", slug: "rav4" }, { name: "C-HR", slug: "c-hr" }, { name: "Aygo", slug: "aygo" }, { name: "Aygo X", slug: "aygo-x" },
      { name: "Camry", slug: "camry" }, { name: "Avensis", slug: "avensis" }, { name: "Avensis Verso", slug: "avensis-verso" },
      { name: "Land Cruiser", slug: "land-cruiser" }, { name: "Land Cruiser V8", slug: "lc-v8" }, { name: "Land Cruiser Prado", slug: "lc-prado" },
      { name: "Hilux", slug: "hilux" }, { name: "Prius", slug: "prius" }, { name: "Prius Plus", slug: "prius-plus" }, { name: "Auris", slug: "auris" }, { name: "Auris Touring Sports", slug: "auris-ts" },
      { name: "Supra", slug: "supra" }, { name: "GT86", slug: "gt86" }, { name: "GR86", slug: "gr86" },
      { name: "Highlander", slug: "highlander" }, { name: "Mirai", slug: "mirai" }, { name: "Proace", slug: "proace" }, { name: "Proace City", slug: "proace-city" },
      { name: "Celica", slug: "celica" }, { name: "MR2", slug: "mr2" }, { name: "Starlet", slug: "starlet" }, { name: "Tercel", slug: "tercel" }, { name: "Previa", slug: "previa" }, { name: "IQ", slug: "iq" }, { name: "Urban Cruiser", slug: "urban-cruiser" }
    ]
  },
  {
    brand: "Peugeot",
    slug: "peugeot",
    models: [
      { name: "106", slug: "106" }, { name: "107", slug: "107" }, { name: "108", slug: "108" },
      { name: "206", slug: "206" }, { name: "206 CC", slug: "206-cc" }, { name: "206 Plus", slug: "206-plus" }, { name: "206 SW", slug: "206-sw" },
      { name: "207", slug: "207" }, { name: "207 CC", slug: "207-cc" }, { name: "207 SW", slug: "207-sw" },
      { name: "208", slug: "208" }, { name: "e-208", slug: "e-208" },
      { name: "306", slug: "306" }, { name: "307", slug: "307" }, { name: "307 CC", slug: "307-cc" }, { name: "307 SW", slug: "307-sw" },
      { name: "308", slug: "308" }, { name: "308 CC", slug: "308-cc" }, { name: "308 SW", slug: "308-sw" }, { name: "e-308", slug: "e-308" },
      { name: "406", slug: "406" }, { name: "406 Coupe", slug: "406-coupe" }, { name: "407", slug: "407" }, { name: "407 Coupe", slug: "407-coupe" }, { name: "407 SW", slug: "407-sw" },
      { name: "508", slug: "508" }, { name: "508 SW", slug: "508-sw" }, { name: "508 RXH", slug: "508-rxh" },
      { name: "607", slug: "607" }, { name: "806", slug: "806" }, { name: "807", slug: "807" },
      { name: "1007", slug: "1007" }, { name: "2008", slug: "2008" }, { name: "e-2008", slug: "e-2008" },
      { name: "3008", slug: "3008" }, { name: "4007", slug: "4007" }, { name: "4008", slug: "4008" }, { name: "5008", slug: "5008" },
      { name: "Bipper", slug: "bipper" }, { name: "Partner", slug: "partner" }, { name: "Partner Tepee", slug: "partner-tepee" }, { name: "Rifter", slug: "rifter" }, { name: "Expert", slug: "expert" }, { name: "Traveller", slug: "traveller" }, { name: "Boxer", slug: "boxer" },
      { name: "RCZ", slug: "rcz" }, { name: "Ion", slug: "ion" }, { name: "301", slug: "301" }
    ]
  },
  {
    brand: "Renault",
    slug: "renault",
    models: [
      { name: "Twingo", slug: "twingo" }, { name: "Clio", slug: "clio" }, { name: "Clio Grandtour", slug: "clio-grandtour" },
      { name: "Megane", slug: "megane" }, { name: "Megane Grandtour", slug: "megane-grandtour" }, { name: "Megane Coupe", slug: "megane-coupe" }, { name: "Megane CC", slug: "megane-cc" }, { name: "Megane E-Tech", slug: "megane-e-tech" },
      { name: "Laguna", slug: "laguna" }, { name: "Laguna Grandtour", slug: "laguna-grandtour" }, { name: "Laguna Coupe", slug: "laguna-coupe" },
      { name: "Talisman", slug: "talisman" }, { name: "Talisman Grandtour", slug: "talisman-grandtour" },
      { name: "Scenic", slug: "scenic" }, { name: "Grand Scenic", slug: "grand-scenic" },
      { name: "Espace", slug: "espace" }, { name: "Grand Espace", slug: "grand-espace" },
      { name: "Captur", slug: "captur" }, { name: "Kadjar", slug: "kadjar" }, { name: "Austral", slug: "austral" }, { name: "Arkana", slug: "arkana" }, { name: "Koleos", slug: "koleos" },
      { name: "Kangoo", slug: "kangoo" }, { name: "Kangoo Express", slug: "kangoo-express" }, { name: "Kangoo Be Bop", slug: "kangoo-bebop" },
      { name: "Master", slug: "master" }, { name: "Trafic", slug: "trafic" }, { name: "Trafic Passenger", slug: "trafic-passenger" }, { name: "Trafic Generation", slug: "trafic-generation" },
      { name: "Fluence", slug: "fluence" }, { name: "Modus", slug: "modus" }, { name: "Grand Modus", slug: "grand-modus" },
      { name: "Vel Satis", slug: "vel-satis" }, { name: "Safrane", slug: "safrane" }, { name: "Avantime", slug: "avantime" },
      { name: "Zoe", slug: "zoe" }, { name: "Twizy", slug: "twizy" }, { name: "R4", slug: "r4" }, { name: "R5", slug: "r5" }, { name: "R9", slug: "r9" }, { name: "R11", slug: "r11" }, { name: "R19", slug: "r19" }, { name: "R21", slug: "r21" }, { name: "R25", slug: "r25" }, { name: "Fuego", slug: "fuego" }
    ]
  },
  {
    brand: "Ford",
    slug: "ford",
    models: [
      { name: "Fiesta", slug: "fiesta" }, { name: "Fiesta Van", slug: "fiesta-van" }, { name: "Fiesta ST", slug: "fiesta-st" },
      { name: "Focus", slug: "focus" }, { name: "Focus Turnier", slug: "focus-turnier" }, { name: "Focus CC", slug: "focus-cc" }, { name: "Focus ST", slug: "focus-st" }, { name: "Focus RS", slug: "focus-rs" },
      { name: "Mondeo", slug: "mondeo" }, { name: "Mondeo Turnier", slug: "mondeo-turnier" }, { name: "Mondeo Vignale", slug: "mondeo-vignale" },
      { name: "Ka", slug: "ka" }, { name: "Ka Plus", slug: "ka-plus" }, { name: "StreetKa", slug: "streetka" },
      { name: "B-Max", slug: "b-max" }, { name: "C-Max", slug: "c-max" }, { name: "Grand C-Max", slug: "grand-c-max" },
      { name: "S-Max", slug: "s-max" }, { name: "Galaxy", slug: "galaxy" },
      { name: "EcoSport", slug: "ecosport" }, { name: "Puma", slug: "puma" }, { name: "Kuga", slug: "kuga" }, { name: "Edge", slug: "edge" }, { name: "Explorer", slug: "explorer" }, { name: "Mustang", slug: "mustang" }, { name: "Mustang Mach-E", slug: "mustang-mach-e" },
      { name: "Ranger", slug: "ranger" }, { name: "Ranger Raptor", slug: "ranger-raptor" },
      { name: "Transit", slug: "transit" }, { name: "Transit Custom", slug: "transit-custom" }, { name: "Transit Connect", slug: "transit-connect" }, { name: "Transit Courier", slug: "transit-courier" },
      { name: "Tourneo Custom", slug: "tourneo-custom" }, { name: "Tourneo Connect", slug: "tourneo-connect" }, { name: "Tourneo Courier", slug: "tourneo-courier" },
      { name: "Fusion", slug: "fusion" }, { name: "Escort", slug: "escort" }, { name: "Orion", slug: "orion" }, { name: "Sierra", slug: "sierra" }, { name: "Scorpio", slug: "scorpio" }, { name: "Probe", slug: "probe" }, { name: "Cougar", slug: "cougar" }, { name: "Capri", slug: "capri" }
    ]
  },
  {
    brand: "Opel",
    slug: "opel",
    models: [
      { name: "Corsa", slug: "corsa" }, { name: "Corsa Van", slug: "corsa-van" }, { name: "e-Corsa", slug: "e-corsa" },
      { name: "Astra", slug: "astra" }, { name: "Astra Caravan", slug: "astra-caravan" }, { name: "Astra Sports Tourer", slug: "astra-st" }, { name: "Astra GTC", slug: "astra-gtc" }, { name: "Astra TwinTop", slug: "astra-twintop" }, { name: "Astra Sedan", slug: "astra-sedan" },
      { name: "Vectra", slug: "vectra" }, { name: "Vectra Caravan", slug: "vectra-caravan" }, { name: "Signum", slug: "signum" },
      { name: "Insignia", slug: "insignia" }, { name: "Insignia Sports Tourer", slug: "insignia-st" }, { name: "Insignia Country Tourer", slug: "insignia-ct" }, { name: "Insignia Grand Sport", slug: "insignia-gs" },
      { name: "Omega", slug: "omega" }, { name: "Omega Caravan", slug: "omega-caravan" }, { name: "Senator", slug: "senator" },
      { name: "Adam", slug: "adam" }, { name: "Karl", slug: "karl" }, { name: "Agila", slug: "agila" },
      { name: "Meriva", slug: "meriva" }, { name: "Zafira", slug: "zafira" }, { name: "Zafira Tourer", slug: "zafira-tourer" }, { name: "Zafira Life", slug: "zafira-life" },
      { name: "Mokka", slug: "mokka" }, { name: "Mokka X", slug: "mokka-x" }, { name: "e-Mokka", slug: "e-mokka" },
      { name: "Crossland", slug: "crossland" }, { name: "Crossland X", slug: "crossland-x" },
      { name: "Grandland", slug: "grandland" }, { name: "Grandland X", slug: "grandland-x" }, { name: "Antara", slug: "antara" }, { name: "Frontera", slug: "frontera" }, { name: "Monterey", slug: "monterey" },
      { name: "Combo", slug: "combo" }, { name: "Combo Life", slug: "combo-life" }, { name: "Vivaro", slug: "vivaro" }, { name: "Movano", slug: "movano" },
      { name: "Calibra", slug: "calibra" }, { name: "Tigra", slug: "tigra" }, { name: "GT", slug: "gt" }, { name: "Speedster", slug: "speedster" }, { name: "Cascada", slug: "cascada" },
      { name: "Kadett", slug: "kadett" }, { name: "Ascona", slug: "ascona" }, { name: "Rekord", slug: "rekord" }, { name: "Manta", slug: "manta" }
    ]
  },
  { brand: "Abarth", slug: "abarth", models: [{ name: "500", slug: "500" }, { name: "595", slug: "595" }, { name: "695", slug: "695" }, { name: "124 Spider", slug: "124-spider" }, { name: "Punto Abarth", slug: "punto" }, { name: "Grande Punto Abarth", slug: "grande-punto" }] },
  { brand: "Alfa Romeo", slug: "alfa-romeo", models: [{ name: "Giulia", slug: "giulia" }, { name: "Stelvio", slug: "stelvio" }, { name: "Giulietta", slug: "giulietta" }, { name: "Mito", slug: "mito" }, { name: "Tonale", slug: "tonale" }, { name: "159", slug: "159" }, { name: "156", slug: "156" }, { name: "147", slug: "147" }, { name: "166", slug: "166" }, { name: "164", slug: "164" }, { name: "145", slug: "145" }, { name: "146", slug: "146" }, { name: "GT", slug: "gt" }, { name: "Brera", slug: "brera" }, { name: "Spider", slug: "spider" }, { name: "GTV", slug: "gtv" }, { name: "4C", slug: "4c" }, { name: "8C", slug: "8c" }, { name: "SZ", slug: "sz" }] },
  { brand: "Alpine", slug: "alpine", models: [{ name: "A110", slug: "a110" }, { name: "A310", slug: "a310" }, { name: "V6 GT", slug: "v6-gt" }] },
  { brand: "Aston Martin", slug: "aston-martin", models: [{ name: "DB11", slug: "db11" }, { name: "DBS", slug: "dbs" }, { name: "DBX", slug: "dbx" }, { name: "Vantage", slug: "vantage" }, { name: "Vanquish", slug: "vanquish" }, { name: "Rapide", slug: "rapide" }, { name: "DB9", slug: "db9" }, { name: "DB7", slug: "db7" }, { name: "Cygnet", slug: "cygnet" }] },
  { brand: "Bentley", slug: "bentley", models: [{ name: "Continental GT", slug: "continental-gt" }, { name: "Flying Spur", slug: "flying-spur" }, { name: "Bentayga", slug: "bentayga" }, { name: "Mulsanne", slug: "mulsanne" }, { name: "Arnage", slug: "arnage" }, { name: "Azure", slug: "azure" }] },
  { brand: "Bugatti", slug: "bugatti", models: [{ name: "Veyron", slug: "veyron" }, { name: "Chiron", slug: "chiron" }, { name: "Divo", slug: "divo" }, { name: "Centodieci", slug: "centodieci" }] },
  { brand: "Buick", slug: "buick", models: [{ name: "Enclave", slug: "enclave" }, { name: "Encore", slug: "encore" }, { name: "Envision", slug: "envision" }, { name: "Regal", slug: "regal" }, { name: "LaCrosse", slug: "lacrosse" }] },
  { brand: "BYD", slug: "byd", models: [{ name: "Atto 3", slug: "atto-3" }, { name: "Han", slug: "han" }, { name: "Tang", slug: "tang" }, { name: "Dolphin", slug: "dolphin" }, { name: "Seal", slug: "seal" }, { name: "Song", slug: "song" }, { name: "Qin", slug: "qin" }] },
  { brand: "Cadillac", slug: "cadillac", models: [{ name: "ATS", slug: "ats" }, { name: "CTS", slug: "cts" }, { name: "CT4", slug: "ct4" }, { name: "CT5", slug: "ct5" }, { name: "CT6", slug: "ct6" }, { name: "XT4", slug: "xt4" }, { name: "XT5", slug: "xt5" }, { name: "XT6", slug: "xt6" }, { name: "Escalade", slug: "escalade" }, { name: "SRX", slug: "srx" }] },
  { brand: "Chevrolet", slug: "chevrolet", models: [{ name: "Cruze", slug: "cruze" }, { name: "Aveo", slug: "aveo" }, { name: "Captiva", slug: "captiva" }, { name: "Spark", slug: "spark" }, { name: "Camaro", slug: "camaro" }, { name: "Corvette", slug: "corvette" }, { name: "Malibu", slug: "malibu" }, { name: "Trax", slug: "trax" }, { name: "Orlando", slug: "orlando" }, { name: "Epica", slug: "epica" }, { name: "Lacetti", slug: "lacetti" }, { name: "Matiz", slug: "matiz" }, { name: "Tahoe", slug: "tahoe" }, { name: "Suburban", slug: "suburban" }, { name: "Silverado", slug: "silverado" }] },
  { brand: "Chrysler", slug: "chrysler", models: [{ name: "300C", slug: "300c" }, { name: "PT Cruiser", slug: "pt-cruiser" }, { name: "Voyager", slug: "voyager" }, { name: "Grand Voyager", slug: "grand-voyager" }, { name: "Crossfire", slug: "crossfire" }, { name: "Sebring", slug: "sebring" }, { name: "Pacifica", slug: "pacifica" }, { name: "Aspen", slug: "aspen" }] },
  { brand: "Citroen", slug: "citroen", models: [{ name: "C1", slug: "c1" }, { name: "C2", slug: "c2" }, { name: "C3", slug: "c3" }, { name: "C3 Aircross", slug: "c3-aircross" }, { name: "C3 Picasso", slug: "c3-picasso" }, { name: "C4", slug: "c4" }, { name: "C4 Picasso", slug: "c4-picasso" }, { name: "C4 Grand Picasso", slug: "c4-grand-picasso" }, { name: "C4 Cactus", slug: "c4-cactus" }, { name: "C4 Aircross", slug: "c4-aircross" }, { name: "C4 X", slug: "c4-x" }, { name: "C5", slug: "c5" }, { name: "C5 Aircross", slug: "c5-aircross" }, { name: "C5 X", slug: "c5-x" }, { name: "C6", slug: "c6" }, { name: "C8", slug: "c8" }, { name: "C-Crosser", slug: "c-crosser" }, { name: "C-Elysee", slug: "c-elysee" }, { name: "Berlingo", slug: "berlingo" }, { name: "Nemo", slug: "nemo" }, { name: "Jumpy", slug: "jumpy" }, { name: "Jumper", slug: "jumper" }, { name: "Spacetourer", slug: "spacetourer" }, { name: "DS3", slug: "ds3" }, { name: "DS4", slug: "ds4" }, { name: "DS5", slug: "ds5" }, { name: "Saxo", slug: "saxo" }, { name: "Xsara", slug: "xsara" }, { name: "Xsara Picasso", slug: "xsara-picasso" }, { name: "Xantia", slug: "xantia" }, { name: "XM", slug: "xm" }, { name: "ZX", slug: "zx" }, { name: "AX", slug: "ax" }, { name: "2CV", slug: "2cv" }] },
  { brand: "Cupra", slug: "cupra", models: [{ name: "Formentor", slug: "formentor" }, { name: "Leon", slug: "leon" }, { name: "Leon Sportstourer", slug: "leon-st" }, { name: "Ateca", slug: "ateca" }, { name: "Born", slug: "born" }, { name: "Tavascan", slug: "tavascan" }] },
  { brand: "Dacia", slug: "dacia", models: [{ name: "Duster", slug: "duster" }, { name: "Sandero", slug: "sandero" }, { name: "Sandero Stepway", slug: "sandero-stepway" }, { name: "Logan", slug: "logan" }, { name: "Logan MCV", slug: "logan-mcv" }, { name: "Logan Van", slug: "logan-van" }, { name: "Logan Pick-up", slug: "logan-pickup" }, { name: "Jogger", slug: "jogger" }, { name: "Lodgy", slug: "lodgy" }, { name: "Dokker", slug: "dokker" }, { name: "Spring", slug: "spring" }, { name: "Solenza", slug: "solenza" }, { name: "SuperNova", slug: "supernova" }, { name: "Nova", slug: "nova" }, { name: "1310", slug: "1310" }] },
  { brand: "Daewoo", slug: "daewoo", models: [{ name: "Matiz", slug: "matiz" }, { name: "Lanos", slug: "lanos" }, { name: "Nubira", slug: "nubira" }, { name: "Kalos", slug: "kalos" }, { name: "Leganza", slug: "leganza" }, { name: "Tacuma", slug: "tacuma" }, { name: "Rezzo", slug: "rezzo" }, { name: "Evanda", slug: "evanda" }, { name: "Tico", slug: "tico" }, { name: "Nexia", slug: "nexia" }, { name: "Espero", slug: "espero" }, { name: "Korando", slug: "korando" }, { name: "Musso", slug: "musso" }] },
  { brand: "Daihatsu", slug: "daihatsu", models: [{ name: "Sirion", slug: "sirion" }, { name: "Terios", slug: "terios" }, { name: "Cuore", slug: "cuore" }, { name: "Charade", slug: "charade" }, { name: "Move", slug: "move" }, { name: "Copen", slug: "copen" }, { name: "Trevis", slug: "trevis" }, { name: "Materia", slug: "materia" }] },
  { brand: "Dodge", slug: "dodge", models: [{ name: "Challenger", slug: "challenger" }, { name: "Charger", slug: "charger" }, { name: "Durango", slug: "durango" }, { name: "Ram", slug: "ram" }, { name: "Nitro", slug: "nitro" }, { name: "Caliber", slug: "caliber" }, { name: "Journey", slug: "journey" }, { name: "Avenger", slug: "avenger" }, { name: "Viper", slug: "viper" }, { name: "Dart", slug: "dart" }, { name: "Magnum", slug: "magnum" }, { name: "Stealth", slug: "stealth" }] },
  { brand: "DS", slug: "ds", models: [{ name: "DS 3", slug: "ds-3" }, { name: "DS 3 Crossback", slug: "ds-3-crossback" }, { name: "DS 4", slug: "ds-4" }, { name: "DS 4 Crossback", slug: "ds-4-crossback" }, { name: "DS 5", slug: "ds-5" }, { name: "DS 7 Crossback", slug: "ds-7-crossback" }, { name: "DS 9", slug: "ds-9" }] },
  { brand: "Ferrari", slug: "ferrari", models: [{ name: "458 Italia", slug: "458" }, { name: "488 GTB", slug: "488" }, { name: "F8 Tributo", slug: "f8" }, { name: "Roma", slug: "roma" }, { name: "Portofino", slug: "portofino" }, { name: "SF90 Stradale", slug: "sf90" }, { name: "812 Superfast", slug: "812" }, { name: "LaFerrari", slug: "laferrari" }, { name: "California", slug: "california" }, { name: "GTC4Lusso", slug: "gtc4lusso" }, { name: "FF", slug: "ff" }, { name: "F12berlinetta", slug: "f12" }, { name: "599 GTB", slug: "599" }, { name: "612 Scaglietti", slug: "612" }, { name: "F430", slug: "f430" }, { name: "360 Modena", slug: "360" }, { name: "F355", slug: "f355" }, { name: "Testarossa", slug: "testarossa" }, { name: "Purosangue", slug: "purosangue" }] },
  { brand: "Fiat", slug: "fiat", models: [{ name: "500", slug: "500" }, { name: "500C", slug: "500c" }, { name: "500e", slug: "500e" }, { name: "500L", slug: "500l" }, { name: "500L Living", slug: "500l-living" }, { name: "500L Trekking", slug: "500l-trekking" }, { name: "500X", slug: "500x" }, { name: "Panda", slug: "panda" }, { name: "Panda 4x4", slug: "panda-4x4" }, { name: "Tipo", slug: "tipo" }, { name: "Tipo Station Wagon", slug: "tipo-sw" }, { name: "Punto", slug: "punto" }, { name: "Punto Evo", slug: "punto-evo" }, { name: "Grande Punto", slug: "grande-punto" }, { name: "Bravo", slug: "bravo" }, { name: "Brava", slug: "brava" }, { name: "Stilo", slug: "stilo" }, { name: "Stilo Multiwagon", slug: "stilo-mw" }, { name: "Doblo", slug: "doblo" }, { name: "Doblo Cargo", slug: "doblo-cargo" }, { name: "Ducato", slug: "ducato" }, { name: "Scudo", slug: "scudo" }, { name: "Fiorino", slug: "fiorino" }, { name: "Qubo", slug: "qubo" }, { name: "Multipla", slug: "multipla" }, { name: "Croma", slug: "croma" }, { name: "Ulysse", slug: "ulysse" }, { name: "Sedici", slug: "sedici" }, { name: "Linea", slug: "linea" }, { name: "Idea", slug: "idea" }, { name: "Marea", slug: "marea" }, { name: "Marea Weekend", slug: "marea-weekend" }, { name: "Palio", slug: "palio" }, { name: "Barchetta", slug: "barchetta" }, { name: "Coupe", slug: "coupe" }, { name: "124 Spider", slug: "124-spider" }, { name: "Freemont", slug: "freemont" }, { name: "Fullback", slug: "fullback" }, { name: "Talento", slug: "talento" }, { name: "Uno", slug: "uno" }, { name: "Cinquecento", slug: "cinquecento" }, { name: "Seicento", slug: "seicento" }, { name: "X1/9", slug: "x1-9" }] },
  { brand: "GMC", slug: "gmc", models: [{ name: "Sierra", slug: "sierra" }, { name: "Yukon", slug: "yukon" }, { name: "Acadia", slug: "acadia" }, { name: "Terrain", slug: "terrain" }, { name: "Canyon", slug: "canyon" }, { name: "Envoy", slug: "envoy" }, { name: "Savana", slug: "savana" }, { name: "Hummer EV", slug: "hummer-ev" }] },
  { brand: "Honda", slug: "honda", models: [{ name: "Civic", slug: "civic" }, { name: "Civic Type R", slug: "civic-type-r" }, { name: "Civic Sedan", slug: "civic-sedan" }, { name: "Civic Tourer", slug: "civic-tourer" }, { name: "CR-V", slug: "cr-v" }, { name: "HR-V", slug: "hr-v" }, { name: "Jazz", slug: "jazz" }, { name: "Accord", slug: "accord" }, { name: "Accord Tourer", slug: "accord-tourer" }, { name: "Insight", slug: "insight" }, { name: "FR-V", slug: "fr-v" }, { name: "Legend", slug: "legend" }, { name: "NSX", slug: "nsx" }, { name: "S2000", slug: "s2000" }, { name: "Prelude", slug: "prelude" }, { name: "Integra", slug: "integra" }, { name: "CR-Z", slug: "cr-z" }, { name: "Stream", slug: "stream" }, { name: "Shuttle", slug: "shuttle" }, { name: "Logo", slug: "logo" }, { name: "e", slug: "e" }] },
  { brand: "Hyundai", slug: "hyundai", models: [{ name: "i10", slug: "i10" }, { name: "i20", slug: "i20" }, { name: "i30", slug: "i30" }, { name: "i30 N", slug: "i30-n" }, { name: "i30 Wagon", slug: "i30-wagon" }, { name: "i30 Fastback", slug: "i30-fastback" }, { name: "i40", slug: "i40" }, { name: "i40 Wagon", slug: "i40-wagon" }, { name: "Tucson", slug: "tucson" }, { name: "Santa Fe", slug: "santa-fe" }, { name: "Grand Santa Fe", slug: "grand-santa-fe" }, { name: "Kona", slug: "kona" }, { name: "Ioniq", slug: "ioniq" }, { name: "Ioniq 5", slug: "ioniq-5" }, { name: "Ioniq 6", slug: "ioniq-6" }, { name: "Nexo", slug: "nexo" }, { name: "Bayon", slug: "bayon" }, { name: "Elantra", slug: "elantra" }, { name: "Getz", slug: "getz" }, { name: "Accent", slug: "accent" }, { name: "Matrix", slug: "matrix" }, { name: "Trajet", slug: "trajet" }, { name: "Atos", slug: "atos" }, { name: "Terracan", slug: "terracan" }, { name: "Galloper", slug: "galloper" }, { name: "Coupe", slug: "coupe" }, { name: "Genesis", slug: "genesis" }, { name: "Veloster", slug: "veloster" }, { name: "ix20", slug: "ix20" }, { name: "ix35", slug: "ix35" }, { name: "ix55", slug: "ix55" }, { name: "H-1", slug: "h-1" }, { name: "H-100", slug: "h-100" }, { name: "Staria", slug: "staria" }] },
  { brand: "Infiniti", slug: "infiniti", models: [{ name: "Q30", slug: "q30" }, { name: "QX30", slug: "qx30" }, { name: "Q50", slug: "q50" }, { name: "Q60", slug: "q60" }, { name: "Q70", slug: "q70" }, { name: "QX50", slug: "qx50" }, { name: "QX70", slug: "qx70" }, { name: "G37", slug: "g37" }, { name: "FX30d", slug: "fx30d" }, { name: "FX35", slug: "fx35" }, { name: "FX37", slug: "fx37" }, { name: "FX45", slug: "fx45" }, { name: "FX50", slug: "fx50" }, { name: "EX30d", slug: "ex30d" }] },
  { brand: "Isuzu", slug: "isuzu", models: [{ name: "D-Max", slug: "d-max" }, { name: "Trooper", slug: "trooper" }, { name: "Rodeo", slug: "rodeo" }, { name: "D-Max Space Cab", slug: "space-cab" }, { name: "D-Max Crew Cab", slug: "crew-cab" }] },
  { brand: "Jaguar", slug: "jaguar", models: [{ name: "XE", slug: "xe" }, { name: "XF", slug: "xf" }, { name: "XF Sportbrake", slug: "xf-sportbrake" }, { name: "XJ", slug: "xj" }, { name: "XJL", slug: "xjl" }, { name: "F-Type", slug: "f-type" }, { name: "E-Pace", slug: "e-pace" }, { name: "F-Pace", slug: "f-pace" }, { name: "I-Pace", slug: "i-pace" }, { name: "S-Type", slug: "s-type" }, { name: "X-Type", slug: "x-type" }, { name: "XK", slug: "xk" }, { name: "XKR", slug: "xkr" }] },
  { brand: "Jeep", slug: "jeep", models: [{ name: "Renegade", slug: "renegade" }, { name: "Compass", slug: "compass" }, { name: "Cherokee", slug: "cherokee" }, { name: "Grand Cherokee", slug: "grand-cherokee" }, { name: "Wrangler", slug: "wrangler" }, { name: "Wrangler Unlimited", slug: "wrangler-unlimited" }, { name: "Gladiator", slug: "gladiator" }, { name: "Patriot", slug: "patriot" }, { name: "Commander", slug: "commander" }, { name: "Avenger", slug: "avenger" }] },
  { brand: "Kia", slug: "kia", models: [{ name: "Ceed", slug: "ceed" }, { name: "Ceed SW", slug: "ceed-sw" }, { name: "Pro_ceed", slug: "pro-ceed" }, { name: "Sportage", slug: "sportage" }, { name: "Sorento", slug: "sorento" }, { name: "Rio", slug: "rio" }, { name: "Picanto", slug: "picanto" }, { name: "Stonic", slug: "stonic" }, { name: "Xceed", slug: "xceed" }, { name: "Niro", slug: "niro" }, { name: "e-Niro", slug: "e-niro" }, { name: "EV6", slug: "ev6" }, { name: "EV9", slug: "ev9" }, { name: "Stinger", slug: "stinger" }, { name: "Soul", slug: "soul" }, { name: "e-Soul", slug: "e-soul" }, { name: "Venga", slug: "venga" }, { name: "Optima", slug: "optima" }, { name: "Optima SW", slug: "optima-sw" }, { name: "Carens", slug: "carens" }, { name: "Carnival", slug: "carnival" }, { name: "Pregio", slug: "pregio" }, { name: "K2500", slug: "k2500" }, { name: "Pride", slug: "pride" }, { name: "Shuma", slug: "shuma" }, { name: "Sephia", slug: "sephia" }, { name: "Clarus", slug: "clarus" }, { name: "Retona", slug: "retona" }, { name: "Cerato", slug: "cerato" }, { name: "Magentis", slug: "magentis" }, { name: "Opirus", slug: "opirus" }] },
  { brand: "Lamborghini", slug: "lamborghini", models: [{ name: "Aventador", slug: "aventador" }, { name: "Huracan", slug: "huracan" }, { name: "Urus", slug: "urus" }, { name: "Gallardo", slug: "gallardo" }, { name: "Murcielago", slug: "murcielago" }, { name: "Revuelto", slug: "revuelto" }, { name: "Diablo", slug: "diablo" }, { name: "Countach", slug: "countach" }] },
  { brand: "Lancia", slug: "lancia", models: [{ name: "Ypsilon", slug: "ypsilon" }, { name: "Delta", slug: "delta" }, { name: "Musa", slug: "musa" }, { name: "Thesis", slug: "thesis" }, { name: "Phedra", slug: "phedra" }, { name: "Lybra", slug: "lybra" }, { name: "Kappa", slug: "kappa" }, { name: "Zeta", slug: "zeta" }, { name: "Thema", slug: "thema" }, { name: "Voyager", slug: "voyager" }, { name: "Fulvia", slug: "fulvia" }, { name: "Stratos", slug: "stratos" }] },
  { brand: "Land Rover", slug: "land-rover", models: [{ name: "Range Rover", slug: "range-rover" }, { name: "Range Rover Sport", slug: "range-rover-sport" }, { name: "Range Rover Velar", slug: "range-rover-velar" }, { name: "Range Rover Evoque", slug: "range-rover-evoque" }, { name: "Discovery", slug: "discovery" }, { name: "Discovery Sport", slug: "discovery-sport" }, { name: "Defender 90", slug: "defender-90" }, { name: "Defender 110", slug: "defender-110" }, { name: "Defender 130", slug: "defender-130" }, { name: "Freelander", slug: "freelander" }] },
  { brand: "Lexus", slug: "lexus", models: [{ name: "IS", slug: "is" }, { name: "ES", slug: "es" }, { name: "GS", slug: "gs" }, { name: "LS", slug: "ls" }, { name: "NX", slug: "nx" }, { name: "RX", slug: "rx" }, { name: "RX L", slug: "rx-l" }, { name: "UX", slug: "ux" }, { name: "LC", slug: "lc" }, { name: "CT", slug: "ct" }, { name: "RC", slug: "rc" }, { name: "SC", slug: "sc" }, { name: "GX", slug: "gx" }, { name: "LX", slug: "lx" }, { name: "RZ", slug: "rz" }] },
  { brand: "Maserati", slug: "maserati", models: [{ name: "Ghibli", slug: "ghibli" }, { name: "Quattroporte", slug: "quattroporte" }, { name: "Levante", slug: "levante" }, { name: "Grecale", slug: "grecale" }, { name: "GranTurismo", slug: "granturismo" }, { name: "GranCabrio", slug: "grancabrio" }, { name: "MC20", slug: "mc20" }, { name: "Spyder", slug: "spyder" }] },
  { brand: "Mazda", slug: "mazda", models: [{ name: "Mazda 2", slug: "mazda-2" }, { name: "Mazda 3", slug: "mazda-3" }, { name: "Mazda 3 Sedan", slug: "mazda-3-sedan" }, { name: "Mazda 5", slug: "mazda-5" }, { name: "Mazda 6", slug: "mazda-6" }, { name: "Mazda 6 Wagon", slug: "mazda-6-wagon" }, { name: "CX-3", slug: "cx-3" }, { name: "CX-30", slug: "cx-30" }, { name: "CX-5", slug: "cx-5" }, { name: "CX-7", slug: "cx-7" }, { name: "CX-9", slug: "cx-9" }, { name: "CX-60", slug: "cx-60" }, { name: "CX-80", slug: "cx-80" }, { name: "MX-5", slug: "mx-5" }, { name: "MX-30", slug: "mx-30" }, { name: "RX-7", slug: "rx-7" }, { name: "RX-8", slug: "rx-8" }, { name: "BT-50", slug: "bt-50" }, { name: "Premacy", slug: "premacy" }, { name: "MPV", slug: "mpv" }, { name: "Tribute", slug: "tribute" }, { name: "121", slug: "121" }, { name: "323", slug: "323" }, { name: "626", slug: "626" }, { name: "Xedos 6", slug: "xedos-6" }, { name: "Xedos 9", slug: "xedos-9" }, { name: "Demio", slug: "demio" }] },
  { brand: "MG", slug: "mg", models: [{ name: "ZS", slug: "zs" }, { name: "HS", slug: "hs" }, { name: "MG4", slug: "mg4" }, { name: "MG5", slug: "mg5" }, { name: "Marvel R", slug: "marvel-r" }, { name: "ZR", slug: "zr" }, { name: "ZT", slug: "zt" }, { name: "MGF", slug: "mgf" }, { name: "TF", slug: "tf" }] },
  { brand: "Mini", slug: "mini", models: [{ name: "One", slug: "one" }, { name: "Cooper", slug: "cooper" }, { name: "Cooper S", slug: "cooper-s" }, { name: "John Cooper Works", slug: "jcw" }, { name: "Countryman", slug: "countryman" }, { name: "Clubman", slug: "clubman" }, { name: "Paceman", slug: "paceman" }, { name: "Cabrio", slug: "cabrio" }, { name: "Coupé", slug: "coupe" }, { name: "Roadster", slug: "roadster" }] },
  { brand: "Mitsubishi", slug: "mitsubishi", models: [{ name: "Lancer", slug: "lancer" }, { name: "Colt", slug: "colt" }, { name: "ASX", slug: "asx" }, { name: "Outlander", slug: "outlander" }, { name: "Pajero", slug: "pajero" }, { name: "Pajero Sport", slug: "pajero-sport" }, { name: "Pajero Pinin", slug: "pajero-pinin" }, { name: "L200", slug: "l200" }, { name: "Eclipse Cross", slug: "eclipse-cross" }, { name: "Space Star", slug: "space-star" }, { name: "Galant", slug: "galant" }, { name: "Carisma", slug: "carisma" }, { name: "Sigma", slug: "sigma" }, { name: "3000 GT", slug: "3000-gt" }, { name: "Grandis", slug: "grandis" }, { name: "Canter", slug: "canter" }] },
  { brand: "Nissan", slug: "nissan", models: [{ name: "Qashqai", slug: "qashqai" }, { name: "Qashqai+2", slug: "qashqai-plus-2" }, { name: "Juke", slug: "juke" }, { name: "X-Trail", slug: "x-trail" }, { name: "Micra", slug: "micra" }, { name: "Note", slug: "note" }, { name: "Navara", slug: "navara" }, { name: "Leaf", slug: "leaf" }, { name: "Ariya", slug: "ariya" }, { name: "Townstar", slug: "townstar" }, { name: "Primastar", slug: "primastar" }, { name: "Interstar", slug: "interstar" }, { name: "Pulsar", slug: "pulsar" }, { name: "Tiida", slug: "tiida" }, { name: "Murano", slug: "murano" }, { name: "Pathfinder", slug: "pathfinder" }, { name: "Patrol", slug: "patrol" }, { name: "Patrol GR", slug: "patrol-gr" }, { name: "Terrano", slug: "terrano" }, { name: "Terrano II", slug: "terrano-2" }, { name: "350Z", slug: "350z" }, { name: "370Z", slug: "370z" }, { name: "GT-R", slug: "gt-r" }, { name: "Primera", slug: "primera" }, { name: "Almera", slug: "almera" }, { name: "Almera Tino", slug: "almera-tino" }, { name: "Sunny", slug: "sunny" }, { name: "Serena", slug: "serena" }, { name: "Vanette", slug: "vanette" }, { name: "NV200", slug: "nv200" }, { name: "NV300", slug: "nv300" }, { name: "NV400", slug: "nv400" }, { name: "Pixo", slug: "pixo" }, { name: "Pixo", slug: "pixo" }] },
  { brand: "Porsche", slug: "porsche", models: [{ name: "911", slug: "911" }, { name: "911 Carrera", slug: "911-carrera" }, { name: "911 Turbo", slug: "911-turbo" }, { name: "911 Targa", slug: "911-targa" }, { name: "Cayenne", slug: "cayenne" }, { name: "Cayenne Coupe", slug: "cayenne-coupe" }, { name: "Macan", slug: "macan" }, { name: "Panamera", slug: "panamera" }, { name: "Panamera Sport Turismo", slug: "panamera-st" }, { name: "Taycan", slug: "taycan" }, { name: " Taycan Cross Turismo", slug: "taycan-ct" }, { name: "718 Cayman", slug: "718-cayman" }, { name: "718 Boxster", slug: "718-boxster" }, { name: "Carrera GT", slug: "carrera-gt" }, { name: "918 Spyder", slug: "918-spyder" }, { name: "924", slug: "924" }, { name: "944", slug: "944" }, { name: "928", slug: "928" }, { name: "968", slug: "968" }] },
  { brand: "Seat", slug: "seat", models: [{ name: "Ibiza", slug: "ibiza" }, { name: "Leon", slug: "leon" }, { name: "Leon Sportstourer", slug: "leon-st" }, { name: "Arona", slug: "arona" }, { name: "Ateca", slug: "ateca" }, { name: "Tarraco", slug: "tarraco" }, { name: "Alhambra", slug: "alhambra" }, { name: "Toledo", slug: "toledo" }, { name: "Altea", slug: "altea" }, { name: "Altea XL", slug: "altea-xl" }, { name: "Altea Freetrack", slug: "altea-freetrack" }, { name: "Exeo", slug: "exeo" }, { name: "Exeo ST", slug: "exeo-st" }, { name: "Mii", slug: "mii" }, { name: "Cordoba", slug: "cordoba" }, { name: "Arosa", slug: "arosa" }, { name: "Inca", slug: "inca" }] },
  { brand: "Smart", slug: "smart", models: [{ name: "Fortwo", slug: "fortwo" }, { name: "Forfour", slug: "forfour" }, { name: "#1", slug: "hash-1" }, { name: "#3", slug: "hash-3" }, { name: "Roadster", slug: "roadster" }] },
  { brand: "Subaru", slug: "subaru", models: [{ name: "Impreza", slug: "impreza" }, { name: "Impreza WRX", slug: "impreza-wrx" }, { name: "Forester", slug: "forester" }, { name: "Outback", slug: "outback" }, { name: "XV", slug: "xv" }, { name: "BRZ", slug: "brz" }, { name: "WRX STI", slug: "wrx-sti" }, { name: "Legacy", slug: "legacy" }, { name: "Justy", slug: "justy" }, { name: "Trezia", slug: "trezia" }, { name: "Tribeca", slug: "tribeca" }, { name: "Levorg", slug: "levorg" }] },
  { brand: "Suzuki", slug: "suzuki", models: [{ name: "Swift", slug: "swift" }, { name: "Vitara", slug: "vitara" }, { name: "SX4", slug: "sx4" }, { name: "SX4 S-Cross", slug: "sx4-s-cross" }, { name: "S-Cross", slug: "s-cross" }, { name: "Ignis", slug: "ignis" }, { name: "Jimny", slug: "jimny" }, { name: "Baleno", slug: "baleno" }, { name: "Swace", slug: "swace" }, { name: "Across", slug: "across" }, { name: "Alto", slug: "alto" }, { name: "Splash", slug: "splash" }, { name: "Wagon R", slug: "wagon-r" }, { name: "Liana", slug: "liana" }, { name: "Grand Vitara", slug: "grand-vitara" }, { name: "Samurai", slug: "samurai" }, { name: "Celerio", slug: "celerio" }, { name: "Kizashi", slug: "kizashi" }] },
  { brand: "Tesla", slug: "tesla", models: [{ name: "Model 3", slug: "model-3" }, { name: "Model S", slug: "model-s" }, { name: "Model X", slug: "model-x" }, { name: "Model Y", slug: "model-y" }, { name: "Roadster", slug: "roadster" }, { name: "Cybertruck", slug: "cybertruck" }] },
  { brand: "Volvo", slug: "volvo", models: [{ name: "XC40", slug: "xc40" }, { name: "XC60", slug: "xc60" }, { name: "XC90", slug: "xc90" }, { name: "S60", slug: "s60" }, { name: "S90", slug: "s90" }, { name: "V40", slug: "v40" }, { name: "V40 Cross Country", slug: "v40-cc" }, { name: "V60", slug: "v60" }, { name: "V60 Cross Country", slug: "v60-cc" }, { name: "V90", slug: "v90" }, { name: "V90 Cross Country", slug: "v90-cc" }, { name: "C40", slug: "c40" }, { name: "EX30", slug: "ex30" }, { name: "EX90", slug: "ex90" }, { name: "S40", slug: "s40" }, { name: "S70", slug: "s70" }, { name: "S80", slug: "s80" }, { name: "V50", slug: "v50" }, { name: "V70", slug: "v70" }, { name: "XC70", slug: "xc70" }, { name: "C30", slug: "c30" }, { name: "C70", slug: "c70" }, { name: "850", slug: "850" }, { name: "940", slug: "940" }, { name: "960", slug: "960" }] },
  { brand: "Zastava", slug: "zastava", models: [{ name: "Yugo", slug: "yugo" }, { name: "Skala", slug: "skala" }, { name: "Florida", slug: "florida" }, { name: "101", slug: "101" }, { name: "128", slug: "128" }, { name: "750", slug: "750" }, { name: "Fića", slug: "fica" }, { name: "Tristać", slug: "tristac" }, { name: "Poli", slug: "poli" }] },
  { brand: "Ostalo", slug: "ostalo", models: [{ name: "Ostalo", slug: "ostalo" }] }
].sort((a, b) => a.brand.localeCompare(b.brand));

// Dodatne marke za popunu do 100+
const ADDITIONAL_BRANDS = [
  "Alpine", "Caterham", "Daewoo", "Daihatsu", "DS", "Fisker", "Genesis", "Great Wall", "Hummer", "Infiniti", "Isuzu", "Iveco", "Karma", "Koenigsegg", "Lada", "Lincoln", "Lotus", "Lynk & Co", "Maybach", "McLaren", "Morgan", "Oldsmobile", "Pagani", "Polestar", "Pontiac", "Ram", "Rimac", "Rolls-Royce", "Rover", "Saab", "SsangYong", "Tata", "Triumph", "TVR", "Vauxhall", "Wiesmann", "Zenvo"
];

ADDITIONAL_BRANDS.forEach(b => {
  if (!AUTOMOTIVE_CATALOG.find(x => x.brand === b)) {
    AUTOMOTIVE_CATALOG.push({
      brand: b,
      slug: b.toLowerCase().replace(/ /g, '-'),
      models: [{ name: "Model", slug: "model" }, { name: "Ostalo", slug: "ostalo" }]
    });
  }
});

AUTOMOTIVE_CATALOG.sort((a, b) => a.brand.localeCompare(b.brand));
