/** Konfiguracija filtera i opcija za marketplace. */

export const DEFAULT_FILTERS = {
  lokacija: '',
  priceMin: '',
  priceMax: '',
  marka: '',
  model: '',
  godisteMin: '',
  godisteMax: '',
  kilometrazaMin: '',
  kilometrazaMax: '',
  gorivo: '',
  mjenjac: '',
  karoserija: '',
  pogon: '',
  stanje: '',
  kubikazaMin: '',
  kubikazaMax: '',
  snagaMin: '',
  snagaMax: '',
  tip: '',
  tipOglasa: '',
  tip_ponude: '',
  tip_nekretnine: '',
  kvadraturaMin: '',
  broj_soba: '',
  sprat: '',
  amenities: '',
  klasaNosivosti: '',
  nosivostKg: '',
  brojOsovina: '',
  radniSati: '',
  brojCilindara: '',
  kabina: '',
  emisioniStandard: '',
  tipDijela: '',
  nacinNaplate: '',
  tipBijela: '',
  energetskaKlasa: '',
  tipNamjestaj: '',
  materijal: '',
  tipZaDjecu: '',
  uzrast: '',
  tipPoljoprivreda: '',
  tipTehnika: '',
  vrstaKucni: '',
  tipModa: '',
  velicinaModa: '',
  tipPoslovi: '',
  tipSport: '',
  tipGradjevina: '',
  tipPokloni: '',
  povodPokloni: '',
};

export const CATEGORIES_WITH_FILTER_PANEL = [
  'nekretnine',
  'auto_dijelovi',
  'usluge',
  'bijela_tehnika',
  'namjestaj',
  'za_djecu',
  'poljoprivreda',
  'tehnika',
  'kucni_ljubimci',
  'moda',
  'poslovi',
  'sport',
  'gradjevina',
  'pokloni_cvijece',
];

export const SORT_OPTIONS: { value: string; label: string }[] = [
  { value: '', label: 'Najnoviji (istaknuti prvo)' },
  { value: 'price_asc', label: 'Cijena: najniža' },
  { value: 'price_desc', label: 'Cijena: najviša' },
];

export const VEHICLE_SUBCATEGORIES_FOR_API = [
  'automobili',
  'motocikli',
  'kamioni',
  'traktori',
  'cetvorotockasi',
  'kombi',
  'autobusi',
  'prikolice',
  'kamperi',
];

export const MAX_UPLOAD_WIDTH = 1200;
export const UPLOAD_JPEG_QUALITY = 0.85;
